### ISSUE TITLE
Implement ID's for the parties

### ISSUE THREAD

**Issue by jnnkB** [Parteiduell/backend#2]
This would made me able to shorten the URL's a lot.

**Comment by redsolver** [comment]
Der Parteiname ist die ID, da immer konsistent.

**Comment by redsolver** [comment]
Ansonsten einfach clientseitig eine Map PARTEINAME -> int machen

**Comment by jnnkB** [comment]
Ist die Reinfolge unter https://api.parteiduell.de/allParties konsitent? Die ändert sich wenn neue Daten dazukommen oder? Weil ich halte es nicht für sinnvoll, dass ich die Map auf der Clientseite implementiere. Es sollte meiner Ansicht nach möglich sein, neue Daten ins Backend einzuspeisen ohne das Frontend dafür anpassen zu müssen.

**Comment by redsolver** [comment]
Naja, der für jede Partei individuelle "Zensurmechanismus" wurde ja jetzt auch auf den Client ausgelagert - da kannst du die Map auch noch hardcoden. Bei unbekannten/neuen Parteien kann ja erstmal der Parteiname als ID verwendet werden.

**Comment by jnnkB** [comment]
Wenn ich die Daten für den "Zensurmechanismus" bei dir Anfragen könnte wäre das natürlich noch besser. Dann hätten wir wieder alles für die Daten relevantes auf Server Seite.
