### ISSUE TITLE
Kommunalwahlkompass für die Kommunalwahlen 2021

### ISSUE THREAD

**Issue by kmille** [Parteiduell/backend#6]
ich habe eben gesehen: für die anstehenden Kommunalwahlen gibt es zwar keinen Wahl-O-Mat, aber einen Kommunalwahlkompass. Der funktioniert genauso und da steht auch was von Open Source. Vlt kommt ihr ja an die Fragen/Antworten ran und baut das ein wenn ihr Lust habt:

https://www.faz.net/wahlkompass
https://vaa.uni-oldenburg.de/wie-wir-arbeiten/
https://www.faz.net/aktuell/rhein-main/region-und-hessen/der-digitale-kommunalwahlkompass-ist-eine-wahlhilfe-im-netz-17204483.html

**Comment by codedust** [comment]
Basiert auf diesem Projekt: https://github.com/open-election-compass/client

**Comment by redsolver** [comment]
Es scheint für jede Kommune unterschiedliche Antworten zu geben, wie wollen wir das sinnvoll in der aktuellen UI umsetzen?

**Comment by jnnkB** [comment]
Wir haben es leider zeitlich nicht hinbekommen und jetzt ist es nicht mehr besonders aktuell.
